package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private BigDecimal idCarrera;
     private BigDecimal escuelaIdEscuela;
     private String nomcarrera;

    public Carrera() {
    }

	
    public Carrera(BigDecimal idCarrera, BigDecimal escuelaIdEscuela) {
        this.idCarrera = idCarrera;
        this.escuelaIdEscuela = escuelaIdEscuela;
    }
    public Carrera(BigDecimal idCarrera, BigDecimal escuelaIdEscuela, String nomcarrera) {
       this.idCarrera = idCarrera;
       this.escuelaIdEscuela = escuelaIdEscuela;
       this.nomcarrera = nomcarrera;
    }
   
    public BigDecimal getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(BigDecimal idCarrera) {
        this.idCarrera = idCarrera;
    }
    public BigDecimal getEscuelaIdEscuela() {
        return this.escuelaIdEscuela;
    }
    
    public void setEscuelaIdEscuela(BigDecimal escuelaIdEscuela) {
        this.escuelaIdEscuela = escuelaIdEscuela;
    }
    public String getNomcarrera() {
        return this.nomcarrera;
    }
    
    public void setNomcarrera(String nomcarrera) {
        this.nomcarrera = nomcarrera;
    }




}


