package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private BigDecimal idCategoria;
     private String descripcion;

    public Categoria() {
    }

	
    public Categoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(BigDecimal idCategoria, String descripcion) {
       this.idCategoria = idCategoria;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


