package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detapres generated by hbm2java
 */
public class Detapres  implements java.io.Serializable {


     private BigDecimal idPrestamo;
     private BigDecimal linea;
     private String productoCodproducto;
     private BigDecimal cantprestamo;
     private BigDecimal productoSedeIdSede;

    public Detapres() {
    }

	
    public Detapres(BigDecimal idPrestamo, String productoCodproducto, BigDecimal productoSedeIdSede) {
        this.idPrestamo = idPrestamo;
        this.productoCodproducto = productoCodproducto;
        this.productoSedeIdSede = productoSedeIdSede;
    }
    public Detapres(BigDecimal idPrestamo, BigDecimal linea, String productoCodproducto, BigDecimal cantprestamo, BigDecimal productoSedeIdSede) {
       this.idPrestamo = idPrestamo;
       this.linea = linea;
       this.productoCodproducto = productoCodproducto;
       this.cantprestamo = cantprestamo;
       this.productoSedeIdSede = productoSedeIdSede;
    }
   
    public BigDecimal getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(BigDecimal idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public BigDecimal getLinea() {
        return this.linea;
    }
    
    public void setLinea(BigDecimal linea) {
        this.linea = linea;
    }
    public String getProductoCodproducto() {
        return this.productoCodproducto;
    }
    
    public void setProductoCodproducto(String productoCodproducto) {
        this.productoCodproducto = productoCodproducto;
    }
    public BigDecimal getCantprestamo() {
        return this.cantprestamo;
    }
    
    public void setCantprestamo(BigDecimal cantprestamo) {
        this.cantprestamo = cantprestamo;
    }
    public BigDecimal getProductoSedeIdSede() {
        return this.productoSedeIdSede;
    }
    
    public void setProductoSedeIdSede(BigDecimal productoSedeIdSede) {
        this.productoSedeIdSede = productoSedeIdSede;
    }




}


