package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detadevol generated by hbm2java
 */
public class Detadevol  implements java.io.Serializable {


     private BigDecimal idDevolucion;
     private BigDecimal linea;
     private String productoCodproducto;
     private BigDecimal cantdevolucion;
     private BigDecimal productoSedeIdSede;

    public Detadevol() {
    }

	
    public Detadevol(BigDecimal idDevolucion, String productoCodproducto, BigDecimal productoSedeIdSede) {
        this.idDevolucion = idDevolucion;
        this.productoCodproducto = productoCodproducto;
        this.productoSedeIdSede = productoSedeIdSede;
    }
    public Detadevol(BigDecimal idDevolucion, BigDecimal linea, String productoCodproducto, BigDecimal cantdevolucion, BigDecimal productoSedeIdSede) {
       this.idDevolucion = idDevolucion;
       this.linea = linea;
       this.productoCodproducto = productoCodproducto;
       this.cantdevolucion = cantdevolucion;
       this.productoSedeIdSede = productoSedeIdSede;
    }
   
    public BigDecimal getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(BigDecimal idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public BigDecimal getLinea() {
        return this.linea;
    }
    
    public void setLinea(BigDecimal linea) {
        this.linea = linea;
    }
    public String getProductoCodproducto() {
        return this.productoCodproducto;
    }
    
    public void setProductoCodproducto(String productoCodproducto) {
        this.productoCodproducto = productoCodproducto;
    }
    public BigDecimal getCantdevolucion() {
        return this.cantdevolucion;
    }
    
    public void setCantdevolucion(BigDecimal cantdevolucion) {
        this.cantdevolucion = cantdevolucion;
    }
    public BigDecimal getProductoSedeIdSede() {
        return this.productoSedeIdSede;
    }
    
    public void setProductoSedeIdSede(BigDecimal productoSedeIdSede) {
        this.productoSedeIdSede = productoSedeIdSede;
    }




}


