package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Encasoli generated by hbm2java
 */
public class Encasoli  implements java.io.Serializable {


     private BigDecimal numsolicitud;
     private Date fechasolicitud;
     private String glosasolicitud;
     private BigDecimal usuarioRutusuario;
     private String estado;
     private String comentario;

    public Encasoli() {
    }

	
    public Encasoli(BigDecimal numsolicitud, BigDecimal usuarioRutusuario) {
        this.numsolicitud = numsolicitud;
        this.usuarioRutusuario = usuarioRutusuario;
    }
    public Encasoli(BigDecimal numsolicitud, Date fechasolicitud, String glosasolicitud, BigDecimal usuarioRutusuario, String estado, String comentario) {
       this.numsolicitud = numsolicitud;
       this.fechasolicitud = fechasolicitud;
       this.glosasolicitud = glosasolicitud;
       this.usuarioRutusuario = usuarioRutusuario;
       this.estado = estado;
       this.comentario = comentario;
    }
   
    public BigDecimal getNumsolicitud() {
        return this.numsolicitud;
    }
    
    public void setNumsolicitud(BigDecimal numsolicitud) {
        this.numsolicitud = numsolicitud;
    }
    public Date getFechasolicitud() {
        return this.fechasolicitud;
    }
    
    public void setFechasolicitud(Date fechasolicitud) {
        this.fechasolicitud = fechasolicitud;
    }
    public String getGlosasolicitud() {
        return this.glosasolicitud;
    }
    
    public void setGlosasolicitud(String glosasolicitud) {
        this.glosasolicitud = glosasolicitud;
    }
    public BigDecimal getUsuarioRutusuario() {
        return this.usuarioRutusuario;
    }
    
    public void setUsuarioRutusuario(BigDecimal usuarioRutusuario) {
        this.usuarioRutusuario = usuarioRutusuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


