package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Encapres generated by hbm2java
 */
public class Encapres  implements java.io.Serializable {


     private BigDecimal idPrestamo;
     private Date fechainicio;
     private Date fechafin;
     private BigDecimal encasoliNumsolicitud;
     private String comentario;

    public Encapres() {
    }

	
    public Encapres(BigDecimal idPrestamo, BigDecimal encasoliNumsolicitud) {
        this.idPrestamo = idPrestamo;
        this.encasoliNumsolicitud = encasoliNumsolicitud;
    }
    public Encapres(BigDecimal idPrestamo, Date fechainicio, Date fechafin, BigDecimal encasoliNumsolicitud, String comentario) {
       this.idPrestamo = idPrestamo;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.encasoliNumsolicitud = encasoliNumsolicitud;
       this.comentario = comentario;
    }
   
    public BigDecimal getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(BigDecimal idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public BigDecimal getEncasoliNumsolicitud() {
        return this.encasoliNumsolicitud;
    }
    
    public void setEncasoliNumsolicitud(BigDecimal encasoliNumsolicitud) {
        this.encasoliNumsolicitud = encasoliNumsolicitud;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


