package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private BigDecimal idEscuela;
     private String nomescuela;

    public Escuela() {
    }

	
    public Escuela(BigDecimal idEscuela) {
        this.idEscuela = idEscuela;
    }
    public Escuela(BigDecimal idEscuela, String nomescuela) {
       this.idEscuela = idEscuela;
       this.nomescuela = nomescuela;
    }
   
    public BigDecimal getIdEscuela() {
        return this.idEscuela;
    }
    
    public void setIdEscuela(BigDecimal idEscuela) {
        this.idEscuela = idEscuela;
    }
    public String getNomescuela() {
        return this.nomescuela;
    }
    
    public void setNomescuela(String nomescuela) {
        this.nomescuela = nomescuela;
    }




}


