package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String codproducto;
     private BigDecimal idCategoria;
     private String nomproducto;
     private Blob imagen;
     private Date fechaingreso;
     private BigDecimal precio;
     private Character estado;
     private String comentario;
     private BigDecimal idSede;

    public Producto() {
    }

	
    public Producto(String codproducto, BigDecimal idCategoria, BigDecimal idSede) {
        this.codproducto = codproducto;
        this.idCategoria = idCategoria;
        this.idSede = idSede;
    }
    public Producto(String codproducto, BigDecimal idCategoria, String nomproducto, Blob imagen, Date fechaingreso, BigDecimal precio, Character estado, String comentario, BigDecimal idSede) {
       this.codproducto = codproducto;
       this.idCategoria = idCategoria;
       this.nomproducto = nomproducto;
       this.imagen = imagen;
       this.fechaingreso = fechaingreso;
       this.precio = precio;
       this.estado = estado;
       this.comentario = comentario;
       this.idSede = idSede;
    }
   
    public String getCodproducto() {
        return this.codproducto;
    }
    
    public void setCodproducto(String codproducto) {
        this.codproducto = codproducto;
    }
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNomproducto() {
        return this.nomproducto;
    }
    
    public void setNomproducto(String nomproducto) {
        this.nomproducto = nomproducto;
    }
    public Blob getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Blob imagen) {
        this.imagen = imagen;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public BigDecimal getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(BigDecimal idSede) {
        this.idSede = idSede;
    }




}


