package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sede generated by hbm2java
 */
public class Sede  implements java.io.Serializable {


     private BigDecimal idSede;
     private String nomsede;

    public Sede() {
    }

	
    public Sede(BigDecimal idSede) {
        this.idSede = idSede;
    }
    public Sede(BigDecimal idSede, String nomsede) {
       this.idSede = idSede;
       this.nomsede = nomsede;
    }
   
    public BigDecimal getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(BigDecimal idSede) {
        this.idSede = idSede;
    }
    public String getNomsede() {
        return this.nomsede;
    }
    
    public void setNomsede(String nomsede) {
        this.nomsede = nomsede;
    }




}


