package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private BigDecimal idStock;
     private String productoCodproducto;
     private BigDecimal prestamostock;
     private BigDecimal saldostock;
     private BigDecimal minstock;
     private BigDecimal maxstock;
     private BigDecimal productoSedeIdSede;

    public Stock() {
    }

	
    public Stock(BigDecimal idStock, String productoCodproducto, BigDecimal productoSedeIdSede) {
        this.idStock = idStock;
        this.productoCodproducto = productoCodproducto;
        this.productoSedeIdSede = productoSedeIdSede;
    }
    public Stock(BigDecimal idStock, String productoCodproducto, BigDecimal prestamostock, BigDecimal saldostock, BigDecimal minstock, BigDecimal maxstock, BigDecimal productoSedeIdSede) {
       this.idStock = idStock;
       this.productoCodproducto = productoCodproducto;
       this.prestamostock = prestamostock;
       this.saldostock = saldostock;
       this.minstock = minstock;
       this.maxstock = maxstock;
       this.productoSedeIdSede = productoSedeIdSede;
    }
   
    public BigDecimal getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(BigDecimal idStock) {
        this.idStock = idStock;
    }
    public String getProductoCodproducto() {
        return this.productoCodproducto;
    }
    
    public void setProductoCodproducto(String productoCodproducto) {
        this.productoCodproducto = productoCodproducto;
    }
    public BigDecimal getPrestamostock() {
        return this.prestamostock;
    }
    
    public void setPrestamostock(BigDecimal prestamostock) {
        this.prestamostock = prestamostock;
    }
    public BigDecimal getSaldostock() {
        return this.saldostock;
    }
    
    public void setSaldostock(BigDecimal saldostock) {
        this.saldostock = saldostock;
    }
    public BigDecimal getMinstock() {
        return this.minstock;
    }
    
    public void setMinstock(BigDecimal minstock) {
        this.minstock = minstock;
    }
    public BigDecimal getMaxstock() {
        return this.maxstock;
    }
    
    public void setMaxstock(BigDecimal maxstock) {
        this.maxstock = maxstock;
    }
    public BigDecimal getProductoSedeIdSede() {
        return this.productoSedeIdSede;
    }
    
    public void setProductoSedeIdSede(BigDecimal productoSedeIdSede) {
        this.productoSedeIdSede = productoSedeIdSede;
    }




}


