package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private BigDecimal idTipousuario;
     private String nomtipousuario;

    public Tipousuario() {
    }

	
    public Tipousuario(BigDecimal idTipousuario) {
        this.idTipousuario = idTipousuario;
    }
    public Tipousuario(BigDecimal idTipousuario, String nomtipousuario) {
       this.idTipousuario = idTipousuario;
       this.nomtipousuario = nomtipousuario;
    }
   
    public BigDecimal getIdTipousuario() {
        return this.idTipousuario;
    }
    
    public void setIdTipousuario(BigDecimal idTipousuario) {
        this.idTipousuario = idTipousuario;
    }
    public String getNomtipousuario() {
        return this.nomtipousuario;
    }
    
    public void setNomtipousuario(String nomtipousuario) {
        this.nomtipousuario = nomtipousuario;
    }




}


