package Entidad;
// Generated 12-jul-2016 17:53:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal rutusuario;
     private String dvusuario;
     private String nomusuario;
     private String paternousuario;
     private String maternousuario;
     private String mailusuario;
     private BigDecimal fono;
     private BigDecimal sedeIdSede;
     private BigDecimal carreraIdCarrera;
     private Character bloqueousuario;
     private String motivobloqueo;
     private BigDecimal loginIdLogin;

    public Usuario() {
    }

	
    public Usuario(BigDecimal rutusuario, BigDecimal sedeIdSede, BigDecimal carreraIdCarrera, BigDecimal loginIdLogin) {
        this.rutusuario = rutusuario;
        this.sedeIdSede = sedeIdSede;
        this.carreraIdCarrera = carreraIdCarrera;
        this.loginIdLogin = loginIdLogin;
    }
    public Usuario(BigDecimal rutusuario, String dvusuario, String nomusuario, String paternousuario, String maternousuario, String mailusuario, BigDecimal fono, BigDecimal sedeIdSede, BigDecimal carreraIdCarrera, Character bloqueousuario, String motivobloqueo, BigDecimal loginIdLogin) {
       this.rutusuario = rutusuario;
       this.dvusuario = dvusuario;
       this.nomusuario = nomusuario;
       this.paternousuario = paternousuario;
       this.maternousuario = maternousuario;
       this.mailusuario = mailusuario;
       this.fono = fono;
       this.sedeIdSede = sedeIdSede;
       this.carreraIdCarrera = carreraIdCarrera;
       this.bloqueousuario = bloqueousuario;
       this.motivobloqueo = motivobloqueo;
       this.loginIdLogin = loginIdLogin;
    }
   
    public BigDecimal getRutusuario() {
        return this.rutusuario;
    }
    
    public void setRutusuario(BigDecimal rutusuario) {
        this.rutusuario = rutusuario;
    }
    public String getDvusuario() {
        return this.dvusuario;
    }
    
    public void setDvusuario(String dvusuario) {
        this.dvusuario = dvusuario;
    }
    public String getNomusuario() {
        return this.nomusuario;
    }
    
    public void setNomusuario(String nomusuario) {
        this.nomusuario = nomusuario;
    }
    public String getPaternousuario() {
        return this.paternousuario;
    }
    
    public void setPaternousuario(String paternousuario) {
        this.paternousuario = paternousuario;
    }
    public String getMaternousuario() {
        return this.maternousuario;
    }
    
    public void setMaternousuario(String maternousuario) {
        this.maternousuario = maternousuario;
    }
    public String getMailusuario() {
        return this.mailusuario;
    }
    
    public void setMailusuario(String mailusuario) {
        this.mailusuario = mailusuario;
    }
    public BigDecimal getFono() {
        return this.fono;
    }
    
    public void setFono(BigDecimal fono) {
        this.fono = fono;
    }
    public BigDecimal getSedeIdSede() {
        return this.sedeIdSede;
    }
    
    public void setSedeIdSede(BigDecimal sedeIdSede) {
        this.sedeIdSede = sedeIdSede;
    }
    public BigDecimal getCarreraIdCarrera() {
        return this.carreraIdCarrera;
    }
    
    public void setCarreraIdCarrera(BigDecimal carreraIdCarrera) {
        this.carreraIdCarrera = carreraIdCarrera;
    }
    public Character getBloqueousuario() {
        return this.bloqueousuario;
    }
    
    public void setBloqueousuario(Character bloqueousuario) {
        this.bloqueousuario = bloqueousuario;
    }
    public String getMotivobloqueo() {
        return this.motivobloqueo;
    }
    
    public void setMotivobloqueo(String motivobloqueo) {
        this.motivobloqueo = motivobloqueo;
    }
    public BigDecimal getLoginIdLogin() {
        return this.loginIdLogin;
    }
    
    public void setLoginIdLogin(BigDecimal loginIdLogin) {
        this.loginIdLogin = loginIdLogin;
    }




}


